"""Add checkout_request_id to Payment

Revision ID: e0a657f673b8
Revises: 3f8cb917b6ea
Create Date: 2025-08-01 09:16:05.931254

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e0a657f673b8'
down_revision = '3f8cb917b6ea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('checkout_request_id', sa.String(), nullable=True))
        batch_op.create_unique_constraint('uq_checkout_request_id', ['checkout_request_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payment', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('checkout_request_id')

    # ### end Alembic commands ###
